### ISSUE TITLE
Remove hypen from Mykomaps page url

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/digitalcommons-ghost-theme#31]
https://digitalcommons.coop/myko-maps/ ->
https://digitalcommons.coop/mykomaps/

**Comment by ColmMassey** [comment]
Make maps singular on first line of the page
Mykomaps maps the solidarity ->
Mykomaps map the solidarity

**Comment by wu-lee** [comment]
Just noticed this and made the edit.  I think this is is now done.

**Comment by ColmDC** [comment]
Should we have https://digitalcommons.coop/myko-maps/ redirect to the hypenless one, in case there are places that link to the old one?

**Comment by wu-lee** [comment]
I'm not sure how to do this on Ghost, it might be simpler just to check the rest of the site for broken links to it.  I don't expect anyone else will have had a chance to link to that page, as it's new.

**Comment by ColmDC** [comment]
okay, let's leave it.
